# Generated by Django 3.0.1 on 2020-01-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novelas', '0002_auto_20200112_2130'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favoritos',
            field=models.ManyToManyField(to='novelas.Novelas'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='historial',
            field=models.ManyToManyField(to='novelas.Allchaps'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkdonaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
