# Generated by Django 3.0.1 on 2020-04-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novelas', '0004_auto_20200422_1411'),
        ('users', '0003_auto_20200421_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='historial',
            field=models.ManyToManyField(to='novelas.allchaps'),
        ),
    ]
