# Generated by Django 3.0.1 on 2020-04-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novelas', '0005_auto_20200423_2315'),
        ('users', '0004_auto_20200422_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='historial',
            field=models.ManyToManyField(to='novelas.allchaps'),
        ),
    ]
