# Generated by Django 3.0.1 on 2020-04-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novelas', '0007_auto_20200426_1535'),
        ('users', '0006_auto_20200423_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='historial',
            field=models.ManyToManyField(to='novelas.allchaps'),
        ),
    ]
