# Generated by Django 3.0.1 on 2020-04-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novelas', '0008_auto_20200428_1738'),
        ('users', '0007_auto_20200426_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='historial',
            field=models.ManyToManyField(to='novelas.allchaps'),
        ),
    ]
