# Generated by Django 3.0.1 on 2020-05-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novelas', '0011_auto_20200502_1845'),
        ('users', '0010_auto_20200502_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='historial',
            field=models.ManyToManyField(to='novelas.allchaps'),
        ),
    ]
