# Generated by Django 3.0.1 on 2020-05-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novelas', '0014_auto_20200502_2304'),
        ('users', '0013_auto_20200502_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='historial',
            field=models.ManyToManyField(to='novelas.allchaps'),
        ),
    ]
