# Generated by Django 3.0.1 on 2020-05-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novelas', '0016_auto_20200503_1828'),
        ('users', '0015_auto_20200503_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='historial',
            field=models.ManyToManyField(to='novelas.allchaps'),
        ),
    ]
