# Generated by Django 3.0.1 on 2020-01-07 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('traductor', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('China', 'Novelas chinas'), ('Japonesa', 'Novela japonesa'), ('Koreana', 'Novela koreana')], max_length=50)),
                ('sinopsis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Allchaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contenido', models.TextField()),
                ('num', models.IntegerField()),
                ('nota', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateTimeField(null=True)),
                ('novel_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novelas.Novelas')),
            ],
        ),
    ]
