# Generated by Django 3.0.1 on 2020-04-22 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novelas', '0003_auto_20200421_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novelas.allchaps'),
        ),
        migrations.AlterField(
            model_name='novelas',
            name='categoria',
            field=models.CharField(choices=[('Novela China', 'Novela china'), ('Novela Japonesa', 'Novela japonesa'), ('Novela Koreana', 'Novela koreana')], max_length=50),
        ),
    ]
