# Generated by Django 3.0.1 on 2020-04-24 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novelas', '0005_auto_20200423_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('Fantasia', 'Fantasia'), ('Horror', 'Horror'), ('Moderno', 'Moderno'), ('Sci-fi', 'Ciencia Ficcion'), ('Romance', 'Romance'), ('Magico', 'Magico'), ('Juegos', 'Video Juegos')], max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novelas.allchaps'),
        ),
        migrations.AddField(
            model_name='novelas',
            name='generos',
            field=models.ManyToManyField(to='novelas.Generos'),
        ),
    ]
