# Generated by Django 3.0.1 on 2020-04-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novelas', '0006_auto_20200423_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelas',
            name='img',
            field=models.ImageField(blank=True, upload_to='portadas_novelas'),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novelas.allchaps'),
        ),
    ]
