# Generated by Django 3.0.1 on 2020-05-01 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novelas', '0008_auto_20200428_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelas',
            name='first_chapter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novelas.allchaps'),
        ),
        migrations.AlterField(
            model_name='novelas',
            name='traductor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
