# Generated by Django 3.0.1 on 2020-05-02 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novelas', '0010_auto_20200502_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelas',
            name='slug_titulo',
            field=models.CharField(default='hola', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novelas.allchaps'),
        ),
    ]
