# Generated by Django 3.0.1 on 2020-05-03 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novelas', '0012_auto_20200502_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='generos',
            name='genre',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novelas.allchaps'),
        ),
        migrations.AlterField(
            model_name='generos',
            name='genero',
            field=models.CharField(max_length=300),
        ),
    ]
