# Generated by Django 3.0.1 on 2020-05-03 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novelas', '0015_auto_20200503_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novelas.allchaps'),
        ),
        migrations.AlterField(
            model_name='generos',
            name='genero_slug',
            field=models.CharField(blank=True, default='accion', max_length=300, null=True),
        ),
    ]
